#############################################################################
# Makefile for building: out_sort
# Generated by qmake (3.0) (Qt 5.1.0) on: ?? ???. 8 18:47:06 2014
# Project:  out_sort.pro
# Template: app
# Command: /home/kit/Qt5.1.0/5.1.0/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile out_sort.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/linux-g++ -I. -I/home/kit/Qt5.1.0/5.1.0/gcc_64/include -I/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets -I/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui -I/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/kit/Qt5.1.0/5.1.0/gcc_64 -Wl,-rpath,/home/kit/Qt5.1.0/5.1.0/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/kit/Qt5.1.0//5.1.0/gcc_64/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/kit/Qt5.1.0/5.1.0/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		file.cpp \
		myfile.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		file.o \
		myfile.o \
		moc_mainwindow.o
DIST          = /home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/spec_pre.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/shell-unix.conf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/unix.conf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/linux.conf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/gcc-base.conf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/g++-base.conf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/g++-unix.conf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/qconfig.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_bootstrap.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_clucene.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_v8.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt_functions.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt_config.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/spec_post.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/default_pre.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/default_pre.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/resolve_config.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/default_post.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qml_debug.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/declarative_debug.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/warn_on.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/resources.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/moc.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/uic.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/thread.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/wayland-scanner.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/exceptions.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/yacc.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/lex.prf \
		out_sort.pro \
		out_sort.pro
QMAKE_TARGET  = out_sort
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = out_sort


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: out_sort.pro /home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/linux-g++/qmake.conf /home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/spec_pre.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/shell-unix.conf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/unix.conf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/linux.conf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/gcc-base.conf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/g++-base.conf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/g++-unix.conf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/qconfig.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_bootstrap.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_clucene.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_v8.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt_functions.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt_config.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/spec_post.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/default_pre.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/default_pre.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/resolve_config.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/default_post.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qml_debug.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/declarative_debug.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/warn_on.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/resources.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/moc.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/uic.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/thread.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/wayland-scanner.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/exceptions.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/yacc.prf \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/lex.prf \
		out_sort.pro \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/lib/libQt5Widgets.prl \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/lib/libQt5Gui.prl \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile out_sort.pro
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/spec_pre.prf:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/shell-unix.conf:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/unix.conf:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/linux.conf:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/gcc-base.conf:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/gcc-base-unix.conf:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/g++-base.conf:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/g++-unix.conf:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/qconfig.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_bootstrap.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_clucene.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_core.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_help.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_network.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_script.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_v8.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt_functions.prf:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt_config.prf:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/linux-g++/qmake.conf:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/spec_post.prf:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/exclusive_builds.prf:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/default_pre.prf:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/default_pre.prf:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/resolve_config.prf:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/default_post.prf:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qml_debug.prf:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/declarative_debug.prf:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/warn_on.prf:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt.prf:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/resources.prf:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/moc.prf:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/opengl.prf:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/uic.prf:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/thread.prf:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/wayland-scanner.prf:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/testcase_targets.prf:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/exceptions.prf:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/yacc.prf:
/home/kit/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/lex.prf:
out_sort.pro:
/home/kit/Qt5.1.0/5.1.0/gcc_64/lib/libQt5Widgets.prl:
/home/kit/Qt5.1.0/5.1.0/gcc_64/lib/libQt5Gui.prl:
/home/kit/Qt5.1.0/5.1.0/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile out_sort.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/out_sort1.0.0 || mkdir -p .tmp/out_sort1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/out_sort1.0.0/ && $(COPY_FILE) --parents mainwindow.h file.h myfile.h .tmp/out_sort1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp file.cpp myfile.cpp .tmp/out_sort1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/out_sort1.0.0/ && (cd `dirname .tmp/out_sort1.0.0` && $(TAR) out_sort1.0.0.tar out_sort1.0.0 && $(COMPRESS) out_sort1.0.0.tar) && $(MOVE) `dirname .tmp/out_sort1.0.0`/out_sort1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/out_sort1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_wayland-server-header_make_all:
compiler_wayland-server-header_clean:
compiler_wayland-client-header_make_all:
compiler_wayland-client-header_clean:
compiler_qtwayland-client-header_make_all:
compiler_qtwayland-client-header_clean:
compiler_qtwayland-server-header_make_all:
compiler_qtwayland-server-header_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: /home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QMainWindow \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qmainwindow.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qwidget.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qwindowdefs.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qglobal.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qconfig.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qfeatures.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsystemdetection.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qprocessordetection.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qglobalstatic.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qbasicatomic.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qgenericatomic.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_integrity.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qoldbasicatomic.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_vxworks.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_power.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_alpha.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_bfin.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_mips.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_s390.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_sh4a.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_sparc.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_x86.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_unix.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmutex.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qlogging.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qflags.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qtypeinfo.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qtypetraits.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsysinfo.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobjectdefs.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qnamespace.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobject.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstring.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qchar.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qbytearray.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qrefcount.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qarraydata.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstringbuilder.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qlist.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qalgorithms.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qiterator.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcoreevent.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qscopedpointer.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmetatype.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qisenum.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobject_impl.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmargins.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qrect.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsize.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qpoint.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpaintdevice.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpalette.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qcolor.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qrgb.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstringlist.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qdatastream.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qiodevice.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qpair.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qregexp.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstringmatcher.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qbrush.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qvector.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qmatrix.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpolygon.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qregion.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qline.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qtransform.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpainterpath.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qimage.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpixmap.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsharedpointer.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qshareddata.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qhash.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qfont.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qfontmetrics.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qfontinfo.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qcursor.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qkeysequence.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qevent.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qvariant.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmap.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qdebug.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qtextstream.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qlocale.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qset.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qurl.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qurlquery.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qfile.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qfiledevice.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qvector2d.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qtouchdevice.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qtabwidget.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qicon.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QInputDialog \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qinputdialog.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qdialog.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qlineedit.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qframe.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qtextcursor.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qtextformat.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpen.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qtextoption.h \
		file.h \
		myfile.h \
		mainwindow.h
	/home/kit/Qt5.1.0//5.1.0/gcc_64/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

compiler_wayland-code_make_all:
compiler_wayland-code_clean:
compiler_qtwayland-client-code_make_all:
compiler_qtwayland-client-code_clean:
compiler_qtwayland-server-code_make_all:
compiler_qtwayland-server-code_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/home/kit/Qt5.1.0/5.1.0/gcc_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QMainWindow \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qmainwindow.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qwidget.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qwindowdefs.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qglobal.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qconfig.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qfeatures.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsystemdetection.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qprocessordetection.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qglobalstatic.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qbasicatomic.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qgenericatomic.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_integrity.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qoldbasicatomic.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_vxworks.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_power.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_alpha.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_bfin.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_mips.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_s390.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_sh4a.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_sparc.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_x86.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_unix.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmutex.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qlogging.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qflags.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qtypeinfo.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qtypetraits.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsysinfo.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobjectdefs.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qnamespace.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobject.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstring.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qchar.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qbytearray.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qrefcount.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qarraydata.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstringbuilder.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qlist.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qalgorithms.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qiterator.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcoreevent.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qscopedpointer.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmetatype.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qisenum.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobject_impl.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmargins.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qrect.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsize.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qpoint.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpaintdevice.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpalette.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qcolor.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qrgb.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstringlist.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qdatastream.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qiodevice.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qpair.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qregexp.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstringmatcher.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qbrush.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qvector.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qmatrix.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpolygon.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qregion.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qline.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qtransform.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpainterpath.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qimage.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpixmap.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsharedpointer.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qshareddata.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qhash.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qfont.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qfontmetrics.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qfontinfo.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qcursor.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qkeysequence.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qevent.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qvariant.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmap.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qdebug.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qtextstream.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qlocale.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qset.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qurl.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qurlquery.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qfile.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qfiledevice.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qvector2d.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qtouchdevice.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qtabwidget.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qicon.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QInputDialog \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qinputdialog.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qdialog.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qlineedit.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qframe.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qtextcursor.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qtextformat.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpen.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qtextoption.h \
		file.h \
		myfile.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QApplication \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qapplication.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcoreapplication.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qeventloop.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qguiapplication.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QMainWindow \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qmainwindow.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qwidget.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qwindowdefs.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qglobal.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qconfig.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qfeatures.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsystemdetection.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qprocessordetection.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qglobalstatic.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qbasicatomic.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qgenericatomic.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_integrity.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qoldbasicatomic.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_vxworks.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_power.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_alpha.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_bfin.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_mips.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_s390.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_sh4a.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_sparc.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_x86.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_unix.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmutex.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qlogging.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qflags.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qtypeinfo.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qtypetraits.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsysinfo.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobjectdefs.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qnamespace.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobject.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstring.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qchar.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qbytearray.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qrefcount.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qarraydata.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstringbuilder.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qlist.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qalgorithms.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qiterator.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcoreevent.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qscopedpointer.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmetatype.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qisenum.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobject_impl.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmargins.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qrect.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsize.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qpoint.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpaintdevice.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpalette.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qcolor.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qrgb.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstringlist.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qdatastream.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qiodevice.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qpair.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qregexp.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstringmatcher.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qbrush.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qvector.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qmatrix.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpolygon.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qregion.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qline.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qtransform.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpainterpath.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qimage.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpixmap.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsharedpointer.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qshareddata.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qhash.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qfont.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qfontmetrics.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qfontinfo.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qcursor.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qkeysequence.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qevent.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qvariant.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmap.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qdebug.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qtextstream.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qlocale.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qset.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qurl.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qurlquery.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qfile.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qfiledevice.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qvector2d.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qtouchdevice.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qtabwidget.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qicon.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QInputDialog \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qinputdialog.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qdialog.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qlineedit.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qframe.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qtextcursor.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qtextformat.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpen.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qtextoption.h \
		file.h \
		myfile.h \
		ui_mainwindow.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/QVariant \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QAction \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qaction.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qactiongroup.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QApplication \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qapplication.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcoreapplication.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qeventloop.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qguiapplication.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qinputmethod.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QButtonGroup \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qbuttongroup.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QHeaderView \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qheaderview.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qabstractitemview.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qabstractitemmodel.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qitemselectionmodel.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qstyleoption.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qabstractspinbox.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qvalidator.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qregularexpression.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qslider.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qabstractslider.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qstyle.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qtabbar.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qrubberband.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QListWidget \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qlistwidget.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qlistview.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QMenu \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qmenu.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QMenuBar \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qmenubar.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QPushButton \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qpushbutton.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qabstractbutton.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QSpinBox \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qspinbox.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QStatusBar \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qstatusbar.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QTabWidget \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QTableWidget \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qtablewidget.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qtableview.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QToolBar \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qtoolbar.h \
		/home/kit/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

file.o: file.cpp file.h \
		myfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o file.o file.cpp

myfile.o: myfile.cpp myfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myfile.o myfile.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

